### PR TITLE
a part of #795 contributing page.

### PR DESCRIPTION
**Pull request by SamYuan1990**
This is my 1st PR and I am starting do some contribution on document.

### CODE REVIEW

**Comment by SamYuan1990** [comment]
may I know if hyperledger-fabric.jfrog.io/fabric-tox able to support running a generated page at local host? for example use localhost:8080/xxx to review my change at local?

**Review by davidkhala — APPROVED** [review]
LGTM

**Comment by SamYuan1990** [comment]
@denyeart could you please help with this PR?(find some one help review on it)

**Comment by SamYuan1990** [comment]
Hi @denyeart，
could you please help with this PR?(find some one help review on it)

**Comment by denyeart** [comment]
The fabric-zh_cn-doc-maintainers are:
@yeasy @guoger @davidkhala @stone-ch 

If you need more Chinese language doc maintainers, I'd suggest to bring it up on Technical Working Group China.

**Comment by davidkhala** [comment]
> may I know if hyperledger-fabric.jfrog.io/fabric-tox able to support running a generated page at local host? for example use localhost:8080/xxx to review my change at local?

I can merge this PR if it is required urgently but I hold on since I wonder whether this fabric-tox question should be answered first.

I have no answer to the question.

**Comment by SamYuan1990** [comment]
> The fabric-zh_cn-doc-maintainers are: @yeasy @guoger @davidkhala @stone-ch
> 
> If you need more Chinese language doc maintainers, I'd suggest to bring it up on Technical Working Group China.

I see, I will check with them and see if we need have a call for maintainer or not.

**Comment by SamYuan1990** [comment]
> The fabric-zh_cn-doc-maintainers are: @yeasy @guoger @davidkhala @stone-ch
> 
> If you need more Chinese language doc maintainers, I'd suggest to bring it up on Technical Working Group China.

Hi @denyeart , @ryjones 

Pre discussed with @zRich we have volunteers from [lfapac-open-source-evangelist](https://github.com/lfapac-open-source-evangelist) and others from community would like to help maintain fabric 2.5 zh document.
But they have their own workflow as:
workflow

or you can find the original picture with link https://github.com/lfapac-open-source-evangelist/translation/blob/main/images/onboarding.png

for details in Chinese
https://github.com/lfapac-open-source-evangelist/translation#%E9%A1%B9%E7%9B%AE%E6%B5%81%E7%A8%8B

Hence, they would like to suggestion as:
1. fork fabric-docs-i18n to https://github.com/lfapac-open-source-evangelist.
2. maintain fabric 2.5 zh document on the fork.
3. pr back once all pages in #795 completed.

WDYT?

**Comment by ryjones** [comment]
@SamYuan1990 go for it

**Comment by denyeart** [comment]
Aligning with lfapac-open-source-evangelist sounds reasonable.

**Pull request merged**
