### PR TITLE
[zh_cn] fix translation error

### PR DESCRIPTION
**Pull request by stone-ch**

### CODE REVIEW

**Comment by stone-ch** [comment]
@davidkhala  pls review

**Comment by davidkhala** [comment]
Review after resolve readthedoc build failure

**Comment by stone-ch** [comment]
我用pr更新了我fork的仓库，第二个commit你可以在merge的时候squarsh掉么，还是需要我在本地rebase再push？ @davidkhala

**Comment by ryjones** [comment]
Please take a look at #195

**Pull request closed without merging**
