### PR TITLE
[zh_CN]Update deploy_chaincode.md

### PR DESCRIPTION
**Pull request by ychyss**
translated into chinese, i will do the leftover later.

### CODE REVIEW

**Comment by stone-ch** [comment]
I convert it to draft,we will review it when you finish it.

By the way, DCO check failed, you should add your signoff, see the details:
https://github.com/hyperledger/fabric-docs-i18n/pull/262/checks?check_run_id=1362006552

**Comment by ychyss** [comment]
thankyou！



---Original---

**Comment by stone-ch** [comment]
Please correct the DCO,  if not I will close this PR later

**Comment by stone-ch** [comment]
Please open a new PR after you fix the DCO.

**Pull request closed without merging**
