### PR TITLE
translated Tutorials » Updating a channel configuration

### PR DESCRIPTION
**Pull request by shichangzhi**
Signed-off-by: shichangzhi <shichangzhi163@163.com>

### CODE REVIEW

**Comment by ODOWDAIBM** [comment]
@shichangzhi I cannot approve, but I would like to thank you for your contribution to i18n. It is wonderful to see the team starting to use this new repository.  Thank you so much, Anthony.

**Comment by stone-ch** [comment]
I will review the translations a little later, thanks for your contribution @shichangzhi .

**Comment by shichangzhi** [comment]
@ODOWDAIBM @stone-ch Ok, I see, thanks for your review.

**Review by stone-ch — APPROVED** [review]
LGTM
This is the first PR in new repo, thanks again @shichangzhi

**Pull request merged**
