### PR TITLE
[ja_JP] Fix typo in README.md and developapps/transactionhandler.md

### PR DESCRIPTION
**Pull request by kawabatas**
i found typos and fixed them.

### CODE REVIEW

**Comment by ryjones** [comment]
Hi,
Could you take a look [at my guide on dco](https://wiki.hyperledger.org/display/CA/Use+GitHub+for+Windows+and+VSCode) and fix the DCO on this commit? Thanks
Ry

**Review by ryjones — CHANGES_REQUESTED** [review]
Please fix DCO and I will merge

**Comment by kawabatas** [comment]
Thanks, I fixed DCO. Please check it 🙇

**Review by ryjones — APPROVED** [review]
Thank you!

**Pull request merged**
