### PR TITLE
Tiny improvement of the translation

### PR DESCRIPTION
**Pull request by lethal233**
As you can see, the translation in the `prereqs.rst` is not so good, since it is kind of strange sentence in Chinese. So I change it into a more natural way

### CODE REVIEW

**Review by davidkhala — CHANGES_REQUESTED** [review]
curl 和git是分开的，从原文的角度来说。`或者你运行curl命令有问题`应该放在`安装 cURL`这一段的里面

**Comment by lethal233** [comment]
> curl 和git是分开的，从原文的角度来说。`或者你运行curl命令有问题`应该放在`安装 cURL`这一段的里面

那我觉得原文中 `or if you have problems running the curl commands.` 这里的`or`应作 `otherwise`（即`否则`） 来翻译，而不是作`或者`来翻译 @davidkhala

**Comment by davidkhala** [comment]
> > curl 和git是分开的，从原文的角度来说。`或者你运行curl命令有问题`应该放在`安装 cURL`这一段的里面
> 
> 那我觉得原文中 `or if you have problems running the curl commands.` 这里的`or`应作 `otherwise`（即`否则`） 来翻译，而不是作`或者`来翻译 @davidkhala

其实`or`也可以完全不翻译，打一个句号，直接以`如果...`开始就行

**Comment by ryjones** [comment]
@lethal233 @davidkhala is it OK to merge as-is and fix wording later?

**Comment by davidkhala** [comment]
> @lethal233 @davidkhala is it OK to merge as-is and fix wording later?

Instead, I prefer to mark it as stale and see should we close it later.

**Comment by ryjones** [comment]
> Instead, I prefer to mark it as stale and see should we close it later.

One goal is to assist first-time contributors with landing commits.

**Pull request closed without merging**
