### PR TITLE
index page translation

### PR DESCRIPTION
**Pull request by nikofebrianur**

### CODE REVIEW

**Comment by nikofebrianur** [comment]
Hi, @ryjones, can you help me with the docs/readthedocs.org:fabric-docs-ja-jp, I don't know how to make it to id_ID, I have followed the instruction at https://hyperledger-fabric.readthedocs.io/en/latest/docs_guide.html#building-on-github, but the steps seem different. Thanks.

**Comment by ryjones** [comment]
Hi, @nikofebrianur . I cherry-picked some of your commits to release-2.5, and cherry-picked this one. The difficulty is your copy of release-2.5 is behind origin. If you get it up-to-date, this will be easier in the future. I think I have all of your changes cherry-picked.

**Comment by ryjones** [comment]
Hi, @nikofebrianur . I cherry-picked some of your commits to release-2.5, and cherry-picked this one. The difficulty is your copy of release-2.5 is behind origin. If you get it up-to-date, this will be easier in the future. I think I have all of your changes cherry-picked. Let me know if [all of your changes](https://fabric-docs-id-id--801.org.readthedocs.build/id/801/) made it by approving this build; I will then merge it.

**Comment by ryjones** [comment]
This is an empty commit. please update your branches

**Pull request closed without merging**
